Angular sample app with assets and nodes table
kelvininc/kelvin-angular-sample-app pull request #1
Opened 2022-03-02 14:23 UTC by GoncaloCamaz

Angular sample app

- Authentication 
- Nodes Table page
- Assets Table page

2022-03-04 10:58 UTC, GoncaloCamaz reviewed
AuthGuard needs changes on the method isAccessAllowed since the second if can be an also or discarded 

```
isAccessAllowed(): Promise<boolean> {
		return new Promise(async (resolve, _) => {
			if (!this.authenticated) {
				this.sessionService.clearSession();
				this.keycloakAngular.login();

				return resolve(false);
			}
			else
			{
				return resolve(true);
			}
		});
	}
```

2022-03-04 12:03 UTC, pedrorebelocosta requested changes

2022-03-04 12:03 UTC, pedrorebelocosta commented on src/app/pages/nodes-list/nodes-list.component.ts
> +const initialState: NodesListState = {
you can move this inside the component itself ;) you won't be able to use the const keyword  (this applies for the other ones)

2022-03-04 12:25 UTC, GoncaloCamaz commented on src/app/app.component.spec.ts
> +    expect(compiled.querySelector('.content span')?.textContent).toContain('kelvin-angular-sample-app app is running!');
In this case I will change the test to another html component check

2022-03-04 12:26 UTC, GoncaloCamaz commented on src/app/app.component.ts
> +		if (!environment.production) {
Will remove

2022-03-04 12:26 UTC, GoncaloCamaz commented on src/app/pages/assets-list/assets-list.component.ts
> +  assetsState: AssetsListState = initialState
Will add semicolons on all instance variables

2022-03-04 12:27 UTC, GoncaloCamaz commented on src/app/pages/nodes-list/nodes-list.component.ts
> +  subscription: Subscription = new Subscription;
It does work but its not necessary, will remove on the next commit

2022-03-04 12:27 UTC, GoncaloCamaz commented on src/app/pages/nodes-list/nodes-list.component.ts
> +export class NodesListComponent implements OnInit {
Will correct as well on the next commit

2022-03-04 12:29 UTC, GoncaloCamaz commented on src/app/pages/nodes-list/nodes-list.component.ts
> +const initialState: NodesListState = {
Will move to the beginning of the component on the next commit

2022-03-07 18:22 UTC, ricardogoncalves89 requested changes

2022-03-07 18:22 UTC, ricardogoncalves89 commented on src/environments/environment.config.ts
> +const MOCK_METADATA: IMetadataSchema = {
I check if you really need these configs

2022-03-10 12:31 UTC, ricardogoncalves89 requested changes

2022-03-10 12:31 UTC, ricardogoncalves89 commented on package.json
> +    "@kelvininc/ui-components": "^0.6.0",
You don't need this dependency only the `@kelvininc/angular-ui-components`

2022-03-10 12:31 UTC, ricardogoncalves89 commented on src/app/pages/assets-list/assets-list.component.html
> +<div className="paginator-buttons-container">
`class` not `className` like react 😉

2022-03-10 12:31 UTC, ricardogoncalves89 commented on src/app/pages/assets-list/assets-list.component.html
> +<div className="paginator-buttons-container">
you don't have any definition for that css class.

2022-03-10 12:31 UTC, ricardogoncalves89 commented on src/app/pages/assets-list/assets-list.component.ts
> +	styleUrls: ['./assets-list.component.scss']
If you don't have any css style in the file you can remove it

2022-03-10 12:31 UTC, ricardogoncalves89 commented on src/app/pages/nodes-list/nodes-list.component.html
> +<div className="paginator-buttons-container">
same

2022-03-10 17:38 UTC, GoncaloCamaz commented on package.json
> +    "@kelvininc/ui-components": "^0.6.0",
Will remove the unnecessary dependency and update to the newer version :)

2022-03-10 17:39 UTC, GoncaloCamaz commented on src/app/pages/assets-list/assets-list.component.html
> +<div className="paginator-buttons-container">
Noob mistake :D Will correct

2022-08-31 00:06 UTC, nelsonmestevao commented
It is now working with our latest version of '@kelvininc/angular-ui-components` :raised_hands:

2022-09-08 21:01 UTC, miguelpinto98 requested changes
It's almost ok. Only some improvements and a security check.

2022-09-08 22:55 UTC, nelsonmestevao commented on src/app/app.module.ts
> +		HomeComponent,
What do you mean? `HomeModule`?

2022-09-09 09:11 UTC, miguelpinto98 commented on src/app/app.module.ts
> +		HomeComponent,
To clarify my suggestion here. The aim here is to create feature/view modules (https://angular.io/guide/feature-modules). So, HomeComponent should be declared inside of HomeModule. An here, we should only use the HomeModule.

2022-11-22 15:51 UTC, miguelpinto98 requested changes
Almost done 😄

2022-11-22 15:51 UTC, miguelpinto98 commented on src/app/app-routing.module.ts
> +		component: HomeComponent,
we also should change `component` to `loadChildren` to enable lazy-module.

For this case we should have something like this:
```
loadChildren: () => import('./pages/home.module').then(m => m.HomeModule)
```

2022-11-23 16:49 UTC, nelsonmestevao commented on src/app/app-routing.module.ts
> +		component: HomeComponent,
Thank you for your suggestions, I believe it is as you suggested :blue_heart:

2022-11-23 17:03 UTC, ricardogoncalves89 approved these changes
🚀

2022-12-22 11:14 UTC, merged